### ISSUE TITLE
Unable to retrieve Artifact with Maven Format

### ISSUE THREAD

**Issue by benjaminlallement** [pivotalservices/artifactory-resource#10]
Hi, 

i am unable to configure an Artifactory Resource to retrieve artifacts posted by Maven with format:
http://your-host-goes-here:8081/artifactory/api/storage/your-path-goes-here/[group-id]/[artifact-id]/[version]/[artifact-id]-[version].jar

"regex" is only resolved in artifact filename but not in sub-folder name.

Help is welcome !

**Comment by philicious** [comment]
@benjaminlallement I had the same issue with this resource and had to get it to work. 
you can build the resource from my repo and try it out
```
docker build -t your.private.repo/artifactory-resource .
```
and as resource_type use
```
- name: artifactory
  type: docker-image
  source:
    repository: your.private.repo/artifactory-resource
    username: USERNAME
    password: PASSWORD
```
