### ISSUE TITLE
Can't open file when providing more than one element

### ISSUE THREAD

**Issue by AlbertoImpl** [pivotalservices/artifactory-resource#32]
Hi! Thanks for creating this resource. 
We would like to use it, but we are having some troubles with it.

We have the following definition:
```
resources:
- name: snapshots-staging-repository-sc
  type: artifactory
  source:
    endpoint: {{scs-artifactory-hostname}}
    repository: "/libs-staging-local"
    regex: "sc-connector-(?<version>)-*.*"
    username: {{scs-artifactory-username}}
    password: {{scs-artifactory-password}}
    skip_ssl_verification: true
```
And added this to the job:
```
  - aggregate:
    - put: snapshots-staging-repository-sc
      params: { file: ./sc-jars/sc-connector/* }
```

However, it states that can't open a file. 
```
curl: Can't open './sc-jars/sc-connector/pom-default.xml
./sc-jars/sc-connector/sc-connector-2.0.2.BUILD-SNAPSHOT-javadoc.jar
./sc-jars/sc-connector/sc-connector-2.0.2.BUILD-SNAPSHOT-sources.jar
./sc-jars/sc-connector/sc-connector-2.0.2.BUILD-SNAPSHOT.jar'!
curl: try 'curl --help' for more information
```
We have more than one item we want to upload. 
Is there any better alternative that having a more restrictive regex and  a `put` for each element to be uploaded?
